### ISSUE TITLE
Add README, LICENSE  and screenshots

### ISSUE THREAD

**Issue by Symbian9** [artem78/s60-gps-tracker-cli#3]
Please, add `README.md`, `LICENSE` and one or more screenshots:

- [ ] https://github.com/artem78/s60-gps-tracker-cli/blob/master/README.md
- [ ] https://github.com/artem78/s60-gps-tracker-cli/blob/master/LICENSE
- [ ] https://github.com/artem78/s60-gps-tracker-cli/blob/master/screenshot.png

**Comment by artem78** [comment]
Done. Thank you for report.
